### ISSUE TITLE
Wrong url redirection in docker container

### ISSUE THREAD

**Issue by SalahAdDin** [zeeshanu/opus#84]
I'm testing in this moment `Opus` inside a `docker` container, serving it since `laravel`, and i get a wrong performance browsing in it:

First time that i click in link `Opus` send me back to the home page, and i don't know why:
![seleccion_341](https://cloud.githubusercontent.com/assets/5034215/25871608/d1d65114-3510-11e7-968f-929a90a5e5ee.png)

I have to try five or six time until send me to the correct section. 

But the other problem i can't understand why happen.

I'm using this compose file for setup in docker:
```yaml
version: '2'

services:
  web:
      image: nginx:stable
      ports:
        - "80:80"
  master:
    build: opus-master
    image: opus-master
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
  redis:
      image: redis:latest
  db:
    image: mysql:latest
    environment:
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=opus
      - MYSQL_USER=uzmantech
      - MYSQL_PASSWORD=opus-wiki-on-docker
  migration:
    image: opus-master
    command: php artisan migrate
    depends_on:
      - db
  key:
    image: opus-master
    command: php artisan key:generate
    depends_on:
      - db
      - migration
  db-seed:
    image: opus-master
    command: php artisan db:seed
    depends_on:
      - db
      - migration
      - key
```

I'm passing the `laravel` server through default `docker` host and the `8000` port.

When i refresh the webpage directly send me to home page, when i make click in the team logo since this section: `http://localhost:8000/teams/uzmantech/settings/integrations`, this send me to the home page.

This performance is very strange:
![seleccion_343](https://cloud.githubusercontent.com/assets/5034215/25872655/3bb9d1f2-3514-11e7-8488-ed7557f2b6ed.png)
![seleccion_344](https://cloud.githubusercontent.com/assets/5034215/25872657/3bf36fac-3514-11e7-88c8-409efe14aa2e.png)
I make click in all links to navigate within the site, in a first time all clicks send me to the home page; after a while i have a normal performance, thanks!, but again i make other click and send me again to the home page and henceforth again all links send me to the home page.

Can anyone explain to me why doesn't works correctly?
